apiVersion: batch/v1
kind: Job
metadata:
  name: import-atlas-data-and-api-call
spec:
  ttlSecondsAfterFinished: 1
  template:
    spec:
      containers:
      - name: mongoexport-import
        image: mongo:4.2
        command: ["/bin/sh", "-c"]
        args:
          - |
            mongoexport --uri=mongodb+srv://$(username):$(password)@cluster0.eldw7p4.mongodb.net/sample_training --collection=posts --type=csv --fields=_id,body,permalink,author,title,tags,comments,date --out=/data/dump.csv &&
            mongoimport --host=mongodb-service.default.svc.cluster.local --db sample_training --collection posts --type csv --headerline --file /data/dump.csv
        envFrom:
          - secretRef:
              name: mongo-credentials     
        volumeMounts:
        - name: dump-csv-storage
          mountPath: /data
      - name: curl-express-api
        image: curlimages/curl:7.79.1
        command: ["/bin/sh", "-c"]
        args:
          - |
            sleep 5 &&
            date=$(date '+%Y-%m-%d %H:%M:%S') &&
            curl -X POST -H "Content-Type: application/json" -d "{\"title\":\"FROM JOB $date\",\"body\":\"FROM JOB $date \"}" $expressapi &&
            curl $expressapi > /data/backup.csv
        env:
        - name: expressapi
          value: http:/express-rest-api-deployment.default.svc.cluster.local/posts
        volumeMounts:
        - name: dump-csv-storage
          mountPath: /data
      volumes:
      - name: dump-csv-storage
        persistentVolumeClaim:
          claimName: mongodb-dump-pvc
      restartPolicy: Never