apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    name: frontend
spec:
  containers:
  - name: frontend-container
    image: node:16
    command: ["/bin/sh", "-c"]
    args:
      - git clone https://github.com/mongodb-developer/mongodb-express-rest-api-example.git &&
        cd mongodb-express-rest-api-example/app &&
        npm install &&
        npm start